// GENERADO por consola/consola.mjs desde consola/productos.json — no editar a mano.
// El orden y qué se publica se administran en el panel Publicaciones de la consola.
const PRODUCTOS=[
 {
  "id": "buzios-navidad-2026",
  "tipo": "especial",
  "orden": 0,
  "img": "img/buzios-navidad-2026.jpg",
  "titulo": "Navidad en Búzios",
  "destino": "Búzios",
  "region": "buzios",
  "salida": "2026-12-21",
  "salidaLabel": "21 dic 2026",
  "regreso": "2026-12-28",
  "regresoConfirmado": false,
  "mes": "2026-12",
  "noches": 7,
  "dias": 8,
  "aerolinea": "LATAM",
  "vueloDirecto": true,
  "hotel": "Pousada dos Coqueiros 3* o similar",
  "regimen": "Desayuno",
  "incluye": [
   "Aéreos directos LATAM con artículo personal y carry on",
   "Traslados aeropuerto–hotel–aeropuerto",
   "7 noches en Pousada dos Coqueiros 3* o similar",
   "Régimen: desayuno",
   "Asistencia al viajero Universal Assistance Excellence"
  ],
  "noIncluye": [
   "Almuerzos y cenas",
   "Excursiones",
   "Gastos personales",
   "Todo lo que no figure en 'incluye'"
  ],
  "recorrido": null,
  "paraQuienSi": "Para pasar Navidad en la playa con vuelo directo, sin escalas ni combinaciones.",
  "paraQuienNo": "No es para quien busca hotel grande con todo incluido: es una pousada de tres estrellas.",
  "precio": {
   "moneda": "USD",
   "cuotas": 4,
   "cuota": 300,
   "total": 1200,
   "final": true,
   "base": "doble",
   "porPersona": true,
   "validez": "[A CONFIRMAR]"
  },
  "operador": null,
  "estado": "disponible"
 },
 {
  "id": "angra-dos-reis-navidad-2026",
  "tipo": "especial",
  "orden": 1,
  "img": "img/angra-dos-reis-navidad-2026.jpg",
  "titulo": "Navidad en Angra dos Reis",
  "destino": "Angra dos Reis",
  "region": "brasil",
  "salida": "2026-12-21",
  "salidaLabel": "21 dic 2026",
  "regreso": "2026-12-28",
  "regresoConfirmado": false,
  "mes": "2026-12",
  "noches": 7,
  "dias": 8,
  "aerolinea": "LATAM",
  "vueloDirecto": true,
  "hotel": "Hotel Samba Angra dos Reis 4* o similar",
  "regimen": "Desayuno",
  "incluye": [
   "Aéreos directos LATAM con artículo personal y carry on",
   "Traslados aeropuerto–hotel–aeropuerto",
   "7 noches en Hotel Samba Angra dos Reis 4* o similar",
   "Régimen: desayuno",
   "Asistencia al viajero Universal Assistance Excellence"
  ],
  "noIncluye": [
   "Almuerzos y cenas",
   "Excursiones",
   "Gastos personales",
   "Todo lo que no figure en 'incluye'"
  ],
  "recorrido": null,
  "paraQuienSi": "Para pasar Navidad frente al mar en Angra, con vuelo directo y hotel cuatro estrellas.",
  "paraQuienNo": "No es para quien quiere ciudad y vida nocturna: Angra es mar, islas y descanso.",
  "precio": {
   "moneda": "USD",
   "cuotas": 4,
   "cuota": 300,
   "total": 1200,
   "final": true,
   "base": "doble",
   "porPersona": true,
   "validez": "[A CONFIRMAR]"
  },
  "operador": null,
  "estado": "disponible"
 },
 {
  "id": "rio-navidad-2026",
  "tipo": "especial",
  "orden": 2,
  "img": "img/rio-navidad-2026.jpg",
  "titulo": "Navidad en Río de Janeiro",
  "destino": "Río de Janeiro",
  "region": "brasil",
  "salida": "2026-12-21",
  "salidaLabel": "21 dic 2026",
  "regreso": "2026-12-28",
  "regresoConfirmado": false,
  "mes": "2026-12",
  "noches": 7,
  "dias": 8,
  "aerolinea": "LATAM",
  "vueloDirecto": false,
  "hotel": "Hotel Augusto's Copacabana 3* o similar",
  "regimen": "Desayuno",
  "incluye": [
   "Aéreos LATAM con artículo personal y carry on",
   "Traslados aeropuerto–hotel–aeropuerto",
   "7 noches en Hotel Augusto's Copacabana 3* o similar",
   "Régimen: desayuno",
   "Asistencia al viajero Universal Assistance Excellence"
  ],
  "noIncluye": [
   "Almuerzos y cenas",
   "Excursiones",
   "Gastos personales",
   "Todo lo que no figure en 'incluye'"
  ],
  "recorrido": null,
  "paraQuienSi": "Para pasar Navidad al sol, en Copacabana, con todo resuelto: vuelo, traslados, hotel y asistencia.",
  "paraQuienNo": "No es para quien busca all inclusive ni hotel 5 estrellas: es un 3 estrellas con desayuno.",
  "precio": {
   "moneda": "USD",
   "cuotas": 4,
   "cuota": 300,
   "total": 1200,
   "final": true,
   "base": "doble",
   "porPersona": true,
   "validez": "[A CONFIRMAR]"
  },
  "operador": null,
  "estado": "disponible"
 },
 {
  "id": "angra-dos-reis-ano-nuevo-2026",
  "tipo": "especial",
  "orden": 3,
  "img": "img/angra-dos-reis-ano-nuevo-2026.jpg",
  "titulo": "Año Nuevo en Angra dos Reis",
  "destino": "Angra dos Reis",
  "region": "brasil",
  "salida": "2026-12-27",
  "salidaLabel": "27 dic 2026",
  "regreso": "2027-01-03",
  "regresoConfirmado": false,
  "mes": "2026-12",
  "noches": 7,
  "dias": 8,
  "aerolinea": "LATAM",
  "vueloDirecto": false,
  "hotel": "Palace Hotel Angra 4* o similar",
  "regimen": "Desayuno",
  "incluye": [
   "Aéreos LATAM con artículo personal y carry on",
   "Traslados aeropuerto–hotel–aeropuerto",
   "7 noches en Palace Hotel Angra 4* o similar",
   "Régimen: desayuno",
   "Asistencia al viajero Universal Assistance Excellence"
  ],
  "noIncluye": [
   "Cena de fin de año",
   "Paseo en barco por las islas",
   "Almuerzos y cenas",
   "Excursiones",
   "Gastos personales"
  ],
  "recorrido": null,
  "paraQuienSi": "Para pasar el fin de año en las islas y el mar calmo de Angra, a tres horas de Río, con todo resuelto.",
  "paraQuienNo": "No es para quien quiere la fiesta de Copacabana: Angra es tranquila, de barco y playa.",
  "precio": {
   "moneda": "USD",
   "cuotas": 4,
   "cuota": 460,
   "total": 1840,
   "final": true,
   "base": "doble",
   "porPersona": true,
   "validez": "[A CONFIRMAR]"
  },
  "operador": null,
  "estado": "disponible"
 },
 {
  "id": "buzios-ano-nuevo-2026",
  "tipo": "especial",
  "orden": 4,
  "img": "img/buzios-ano-nuevo-2026.jpg",
  "titulo": "Año Nuevo en Búzios",
  "destino": "Búzios",
  "region": "brasil",
  "salida": "2026-12-27",
  "salidaLabel": "27 dic 2026",
  "regreso": "2027-01-03",
  "regresoConfirmado": false,
  "mes": "2026-12",
  "noches": 7,
  "dias": 8,
  "aerolinea": "LATAM",
  "vueloDirecto": false,
  "hotel": "Pousada dos Coqueiros 3* o similar",
  "regimen": "Desayuno",
  "incluye": [
   "Aéreos LATAM con artículo personal y carry on",
   "Traslados aeropuerto–hotel–aeropuerto",
   "7 noches en Pousada dos Coqueiros 3* o similar",
   "Régimen: desayuno",
   "Asistencia al viajero Universal Assistance Excellence"
  ],
  "noIncluye": [
   "Cena de fin de año",
   "Almuerzos y cenas",
   "Excursiones",
   "Gastos personales"
  ],
  "recorrido": null,
  "paraQuienSi": "Para el fin de año en Búzios: playas de día y la Rua das Pedras de noche, sin manejar.",
  "paraQuienNo": "No es para quien busca hotel grande con todo incluido: es una pousada de tres estrellas.",
  "precio": {
   "moneda": "USD",
   "cuotas": 4,
   "cuota": 350,
   "total": 1400,
   "final": true,
   "base": "doble",
   "porPersona": true,
   "validez": "[A CONFIRMAR]"
  },
  "operador": null,
  "estado": "disponible"
 },
 {
  "id": "rio-reveillon-2026",
  "tipo": "especial",
  "orden": 5,
  "img": "img/rio-reveillon-2026.jpg",
  "titulo": "Año Nuevo en Río de Janeiro",
  "destino": "Río de Janeiro",
  "region": "brasil",
  "salida": "2026-12-27",
  "salidaLabel": "27 dic 2026",
  "regreso": "2027-01-03",
  "regresoConfirmado": false,
  "mes": "2026-12",
  "noches": 7,
  "dias": 8,
  "aerolinea": "LATAM",
  "vueloDirecto": false,
  "hotel": "Hotel Wyndham Barra 3* o similar",
  "regimen": "Desayuno",
  "incluye": [
   "Aéreos LATAM con artículo personal y carry on",
   "Traslados aeropuerto–hotel–aeropuerto",
   "7 noches en Hotel Wyndham Barra 3* o similar",
   "Régimen: desayuno",
   "Asistencia al viajero Universal Assistance Excellence"
  ],
  "noIncluye": [
   "Cena de fin de año",
   "Almuerzos y cenas",
   "Excursiones",
   "Gastos personales"
  ],
  "recorrido": null,
  "paraQuienSi": "Para recibir el año en la playa, con la fiesta de Copacabana a un rato de Barra, y volver con todo resuelto.",
  "paraQuienNo": "No es para quien quiere dormir en Copacabana mismo: el hotel está en Barra da Tijuca. Tampoco incluye la cena de fin de año.",
  "precio": {
   "moneda": "USD",
   "cuotas": 4,
   "cuota": 540,
   "total": 2160,
   "final": true,
   "base": "doble",
   "porPersona": true,
   "validez": "[A CONFIRMAR]"
  },
  "operador": null,
  "estado": "disponible"
 }
];
const DESTINOS=[{"destino":"Búzios","region":"buzios","ids":["buzios-navidad-2026","buzios-ano-nuevo-2026"]},{"destino":"Angra dos Reis","region":"brasil","ids":["angra-dos-reis-navidad-2026","angra-dos-reis-ano-nuevo-2026"]},{"destino":"Río de Janeiro","region":"brasil","ids":["rio-navidad-2026","rio-reveillon-2026"]}];
